### ISSUE TITLE
What does the clipboard icon do?

### ISSUE THREAD

**Issue by losttime** [notwaldorf/polymer-demo-transmogrifier#3]
The clipboard icon is clickable and it animates when clicked, but I can't tell what it's doing (if anything). Is it supposed to do something or is it just for looks?

Neat element, btw!

**Comment by notwaldorf** [comment]
It copies the code it's displayed next to to your clipboard, so that you can paste it :)
I should really add a toast to tell you about that...

**Comment by losttime** [comment]
Ahh, nice. Makes sense. Yes, a toast and/or a hover tooltip would help.
